!!!!!!!!!!!!!!
!!! SYSTEM !!!
!!!!!!!!!!!!!!

DROP USER alex CASCADE;
DROP USER andrea CASCADE;

CREATE USER "ALEX"
PROFILE "DEFAULT"
IDENTIFIED BY "oracle"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "USERS"
ACCOUNT UNLOCK;

GRANT CONNECT  TO alex;
GRANT RESOURCE TO alex;

CREATE TABLE alex.customer
(
  customer_id  INTEGER PRIMARY KEY,
  first_name   VARCHAR(20),
  balance      DECIMAL(10,2)
);

CREATE USER "ANDREA"
PROFILE "DEFAULT"
IDENTIFIED BY "oracle"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "USERS"
ACCOUNT UNLOCK;
GRANT CONNECT  TO andrea;
GRANT RESOURCE TO andrea;
GRANT SELECT, DELETE, INSERT, UPDATE ON alex.customer TO andrea;